name: example
version: 0.0.1
description: >
  Just an example, not for publishing.
authors:
- Marek Gocał <marcin.gocal@gmail.com>
homepage: https://github.com/gocal/bokeh.dart

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  built_collection: '>=2.0.0 <5.0.0'
  bokeh:
    path: ../bokeh

dev_dependencies:
  build_runner: ^1.0.0
  bokeh_gen: '>=0.0.2 <0.1.0'
  pedantic: ^1.4.0
  quiver: '>=0.21.0 <3.0.0'
  test: ^1.0.0


