name: example
version: 0.0.1
description: >
  Just an example, not for publishing.
authors:
- Marek Gocał <marcin.gocal@gmail.com>
homepage: https://github.com/gocal/bokeh.dart

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  bloc:
  bokeh:
    path: ../bokeh

dev_dependencies:
  build_runner: ^1.0.0
  bokeh_generator:
    path: ../bokeh_generator



