name: bokeh
version: 0.1.0
description: Bloc Boilerplate generator
homepage: https://github.com/gocal/bokeh.dart

environment:
  sdk: '>=2.6.0 <3.0.0'
  meta: ^1.1.8
dev_dependencies:
  pedantic: ^1.4.0
  test: ^1.0.0
