targets:
  $default:
    builders:
      bokeh_gen|bokeh:
        enabled: true

builders:
  bokeh:
    target: ":bokeh_generator"
    import: "package:bokeh_generator/bokeh_generator.dart"
    builder_factories: ["bokeh"]
    build_extensions: {".dart": [".g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]