name: bokeh_generator
version: 0.1.0
description: Bloc Boilerplate generator
homepage: https://github.com/gocal/bokeh.dart

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  build: ">=1.2.0 <1.3.0"
  source_gen: ">=0.9.0 <0.10.0"
  code_builder: ">=3.2.0 <3.3.0"
  dart_style: ">=1.3.0 <1.4.0"
  analyzer: ">=0.39.0 <0.40.0"
  recase: ^3.0.0
  #bokeh: '>=0.1.0 <0.1.0'
  bokeh:
    path: ../bokeh

dev_dependencies:
  build_test:
  build_runner:
  test:
