name: bokeh_gen
version: 0.0.2
description: >
  Immutable Data Class Generator
authors:
- Marcin Marek Gocał <marcin.gocal@gmail.com>
homepage: https://github.com/gocal/bokeh.dart

environment:
  sdk: '>=2.0.0-dev <3.0.0'
  build: ^1.0.0
  source_gen: ^0.9.0

dependencies:
  analyzer: '>=0.34.0 <0.37.0'
  build: '>=0.12.0 <2.0.0'  
  source_gen: ^0.9.0  
  bokeh: '>=0.0.1 <0.1.0'

dev_dependencies:
  build_test: ^0.10.3
  build_runner: ^1.0.0
  logging: ^0.11.0
  pedantic: ^1.4.0
  test: ^1.0.0

dependency_overrides:
  bokeh:
    path: ../bokeh